### ISSUE TITLE
Is not jdbcType supported?

### ISSUE THREAD

**Issue by littlehongkong** [OldBlackJoe/mybatis-mapper#6]
Is not jdbcType supported?

What if you want to enter a null value?

**Comment by OldBlackJoe** [comment]
mybatis-mapper does not support jdbcType option, because it is a JDBC requirement, not a MyBatis one.
But, apart from that, it is bug that null parameters are not converted. It is correct that an undefined variable is not converted, but a variable declared as null should be converted. This bug is fixed in 0.6.3. Thank you for your issue!
